config/routes.rb
Rails.application.routes.draw do

  root to: "urls#new"
  resources :urls
  get "/u/:short_url", to: "short_urls#show", as: :short_url

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :long_url, uniqueness: true
  validates :long_url, presence: true
  before_save :generate_short_url
  def generate_short_url
    self.short_url = SecureRandom.hex(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  def show
    @url = Url.find_by(short_url: params[:short_url])
    redirect_to @url.long_url
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    if @url.save
      redirect_to @url
    else
      render :new
    end
  end
  def show
    @url = Url.find(params[:id])
  end
  private
  def url_params
    params.require(:url).permit(:long_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinyapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/new.html.erb
<h1>enter your url </h1>
<% if @url.errors %>
  <% @url.errors.full_messages.each do |msg| %>
    <p> <%= msg %> </p>
  <%end%>
<%end%>
<%= form_for @url do |f|%>
  <%=f.label :long_url%>
  <%=f.text_field :long_url%>
  <%=f.submit%>
<%end%>

app/views/urls/show.html.erb
<h1><%= @url.long_url %></h1>
<%= link_to short_url_url(@url.short_url), short_url_path(@url.short_url) %>